python3 train_lora.py `
  --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" `
  --instance_data_dir="imgs" `
  --output_dir="./lora_weight" `
  --instance_prompt="a cute yellow chubby dragon toy, sks_dragon" `
  --resolution=512 `
  --train_batch_size=1 `
  --gradient_accumulation_steps=4 `
  --learning_rate=1e-4 `
  --lr_scheduler="cosine" `
  --lr_warmup_steps=40 `
  --max_train_steps=3000 `
  --checkpointing_steps=100 `
  --use_8bit_adam `
  --gradient_checkpointing `
  --mixed_precision="fp16"